### ISSUE TITLE
addCurrentMessage() ?

### ISSUE THREAD

**Issue by aoloe** [Neoflow/FlashMessages#3]
I normally plan to add the Flash Message to next.

But, I currently have one use case for messages that need to be rendered in the current session. And I'd prefer not to use a second library just for that...

I'd like to suggest to add `addCurrentMessage` to `Flash.php`.

(Of course I could use `getCurrent()` and `setCurrent()` but that's a huge hack!)

I can make a pull request if you agree with the idea.

**Comment by Alpine418** [comment]
I've added the method. Please update the lib to get the latest released version 1.1.0 of the lib.
