### ISSUE TITLE
Make the project compatible with php 8.0

### ISSUE THREAD

**Issue by aoloe** [Neoflow/FlashMessages#4]
I'm using FlashMessages with PHP 8.0.x and it works well.

Can you please update `composer.json` to accept versions of PHP that are newer than 7.4?

As an example by setting

```
"php": ">=7.3"
```

or

```
"php": "^7.3 ||^8.0"
```

(supposing that it has not been tested with 8.1...

**Comment by Alpine418** [comment]
You are right. I will take a look into it.

**Comment by Alpine418** [comment]
Fixed. Please update to the latest release 1.2.0
